services:
  whisper-diarize:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./output:/output
      - ./models:/app/models
      - ./hf_cache:/config/.cache/huggingface
    environment:
      - HF_TOKEN=${HF_TOKEN}
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-1.0}'
    # To run without creating orphan containers, use:
    # docker pull linuxserver/faster-whisper:latest
    # docker compose build --no-cache whisper-diarize
    # docker compose run --rm whisper-diarize --help